:global:
  componentName: rook-ceph
  feature_goldenTests: true
  testMatrix:
    key: provider
    entries:
      - defaults
      - openshift4


docs/antora.yml:
  name: rook-ceph
  title: Rook Ceph
