:global:
  componentName: rook-ceph
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - openshift4


docs/antora.yml:
  name: rook-ceph
  title: Rook Ceph

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
