:global:
  componentName: Rook Ceph
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - openshift4


.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
