= Alert rule: CephMgrIsAbsent

== icon:glasses[] Overview

This alert fires if Prometheus can't scrape metrics from Ceph.
When this alert fires, no alerts regarding Ceph cluster health can fire because the required metrics aren't available.

== icon:bug[] Steps for debugging

=== Check if the MGR pod is running

.Expected cluster state
[source,console]
----
$ ceph_cluster_ns=syn-rook-ceph-cluster
$ kubectl -n "${ceph_cluster}" get pods -l app=rook-ceph-mgr
NAME                               READY   STATUS    RESTARTS   AGE
rook-ceph-mgr-a-564ddc798c-ztvrd   1/1     Running   0          6d1h
----

If the command above doesn't show any pods, verify that the xref:runbooks/RookCephOperatorScaledDown.adoc[Rook-Ceph operator is running].

If the operator is running, check that the `CephCluster` resource is healthy.

[source,console]
----
$ ceph_cluster_ns=syn-rook-ceph-cluster
$ kubectl -n "${ceph_cluster}" describe cephcluster
[ ... metadata and spec omitted ... ]
Status:
  Ceph:
    Capacity:
      Bytes Available:  305409896448
      Bytes Total:      578156433408
      Bytes Used:       272746536960
      Last Updated:     2021-07-13T12:02:48Z
    Health:             HEALTH_OK <1>
    Last Changed:       2021-07-13T09:18:38Z <2>
    Last Checked:       2021-07-13T12:02:48Z
    Previous Health:    HEALTH_WARN
    Versions:
      Mgr:
        ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable):  1
      Mon:
        ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable):  3
      Osd:
        ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable):  3
      Overall:
        ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable):  7
  Conditions:
    Last Heartbeat Time:   2021-07-13T12:02:48Z
    Last Transition Time:  2021-07-06T18:07:00Z
    Message:               Cluster created successfully
    Reason:                ClusterCreated
    Status:                True
    Type:                  Ready <3>
  Message:                 Cluster created successfully
  Phase:                   Ready
  State:                   Created
  Storage:
    Device Classes:
      Name:  hdd
  Version:
    Image:    docker.io/ceph/ceph:v16.2.4
    Version:  16.2.4-0
----
<1> Current Ceph cluster health
<2> Time of last Ceph cluster health status change
<3> Current condition of `CephCluster` resource

If the current condition of the `CephCluster` resource (<3>) is not `Ready`, check the Rook-Ceph operator logs for any errors.

[source,console]
----
$ ceph_operator_ns=syn-rook-ceph-operator
$ kubectl -n "${ceph_operator_ns}" logs deploy/rook-ceph-operator --since=2h <1>
----
<1> Adjust parameter `--since` depending on the age of the alert

=== Check that Prometheus can scrape the MGR pod

If the `kubectl exec` command in the snippet below hangs or otherwise fails, check

* Node to node firewall rules, since we're running Ceph in host network mode
* Network policies between the Prometheus namespace and the Ceph cluster namespace

[source,console]
----
$ ceph_cluster_ns=syn-rook-ceph-cluster
$ mgr_ip=$(kubectl -n "${ceph_cluster_ns}" get pods -l app=rook-ceph-mgr \
      -o jsonpath='{.items[0].status.podIP}')
$ monitoring_ns=openshift-monitoring <1>
$ prometheus_pod=$(kubectl -n ${monitoring_ns} get pods -l app=prometheus \
      -o jsonpath='{.items[0].metadata.name}')
$ kubectl -n "${monitoring_ns}" exec -it "${prometheus_pod}" -- \
      curl "http://${mgr_ip}:9283/metrics"
[ ... metrics output omitted ... ]
----
<1> Replace the namespace depending on your K8s distribution
