apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-forwarder
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/created-by: christian.haeusler
    app.kubernetes.io/part-of: "github.com-projectsyn-component-rook-ceph"
rules:
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
